library(dplyr)
library(data.table)
data <- fread("./household_power_consumption.txt", na.strings="?",stringsAsFactors = FALSE)
subSetData <- filter(data, grep("^[1,2]/2/2007", Date))
#str(subSetData)
globalActivePower <- as.numeric(subSetData$Global_active_power)
png("plot1.png", width=480, height=480)
hist(globalActivePower, col="red", main="Global Active Power", xlab="Global Active Power (kilowatts)")
dev.off()